apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    annotations:
        description: 'src: (tag = Gryffindor) dst: (tag = Slytherin and tag != DB) conn: All Connections'
        nsx-id: "1925"
    creationTimestamp: null
    name: policy-0
    namespace: default
spec:
    egress:
        - to:
            - podSelector:
                matchExpressions:
                    - key: tag__Slytherin
                      operator: Exists
                    - key: tag__DB
                      operator: DoesNotExist
    podSelector:
        matchExpressions:
            - key: tag__Gryffindor
              operator: Exists
    policyTypes:
        - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    annotations:
        description: 'src: (*) dst: (tag = Slytherin and tag != DB) conn: All Connections'
        nsx-id: "1925"
    creationTimestamp: null
    name: policy-1
    namespace: default
spec:
    ingress:
        - from:
            - podSelector: {}
    podSelector:
        matchExpressions:
            - key: tag__Slytherin
              operator: Exists
            - key: tag__DB
              operator: DoesNotExist
    policyTypes:
        - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    annotations:
        description: 'src: (*) dst: (tag = Gryffindor and tag != DB) conn: All Connections'
        nsx-id: "1926"
    creationTimestamp: null
    name: policy-2
    namespace: default
spec:
    egress:
        - to:
            - podSelector:
                matchExpressions:
                    - key: tag__Gryffindor
                      operator: Exists
                    - key: tag__DB
                      operator: DoesNotExist
    podSelector: {}
    policyTypes:
        - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    annotations:
        description: 'src: (*) dst: (tag = Gryffindor and tag != DB) conn: All Connections'
        nsx-id: "1926"
    creationTimestamp: null
    name: policy-3
    namespace: default
spec:
    ingress:
        - from:
            - podSelector: {}
    podSelector:
        matchExpressions:
            - key: tag__Gryffindor
              operator: Exists
            - key: tag__DB
              operator: DoesNotExist
    policyTypes:
        - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    annotations:
        description: 'src: (*) dst: (tag = Hufflepuff and tag != DB) conn: All Connections'
        nsx-id: "1927"
    creationTimestamp: null
    name: policy-4
    namespace: default
spec:
    egress:
        - to:
            - podSelector:
                matchExpressions:
                    - key: tag__Hufflepuff
                      operator: Exists
                    - key: tag__DB
                      operator: DoesNotExist
    podSelector: {}
    policyTypes:
        - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    annotations:
        description: 'src: (*) dst: (tag = Hufflepuff and tag != DB) conn: All Connections'
        nsx-id: "1927"
    creationTimestamp: null
    name: policy-5
    namespace: default
spec:
    ingress:
        - from:
            - podSelector: {}
    podSelector:
        matchExpressions:
            - key: tag__Hufflepuff
              operator: Exists
            - key: tag__DB
              operator: DoesNotExist
    policyTypes:
        - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    annotations:
        description: Default Deny Network Policy
        nsx-id: "2144"
    creationTimestamp: null
    name: default-deny
    namespace: default
spec:
    podSelector: {}
    policyTypes:
        - Ingress
        - Egress
