apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    labels:
        group__Slytherin: "true"
        group__Web: "true"
    name: Slytherin-Web
spec:
    containers: null
status: {}
---
apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    labels:
        group__App: "true"
        group__Slytherin: "true"
    name: Slytherin-App
spec:
    containers: null
status: {}
---
apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    labels:
        group__Gryffindor: "true"
        group__Web: "true"
    name: Gryffindor-Web
spec:
    containers: null
status: {}
---
apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    labels:
        group__App: "true"
        group__Gryffindor: "true"
    name: Gryffindor-App
spec:
    containers: null
status: {}
