apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
    creationTimestamp: null
    name: udn-T1-192-168-0-0
    namespace: T1-192-168-0-0
spec:
    layer2:
        ipam:
            lifecycle: Persistent
        role: Primary
        subnets:
            - 192.168.0.0/24
    topology: Layer2
status: {}
