apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    labels:
        VMs_within_IPs__0.0.1.0-25: "true"
        group__default-group: "true"
    name: A
    namespace: default
spec:
    containers: null
status: {}
---
apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    labels:
        VMs_within_IPs__0.0.1.128-25: "true"
        group__default-group: "true"
    name: B
    namespace: default
spec:
    containers: null
status: {}
---
apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    labels:
        VMs_within_IPs__0.0.2.0-24: "true"
        group__default-group: "true"
    name: C-no-address
    namespace: default
spec:
    containers: null
status: {}
