apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
    creationTimestamp: null
    name: A
    namespace: default
spec:
    template:
        metadata:
            creationTimestamp: null
            labels:
                group__frontend: "true"
        spec:
            domain:
                devices: {}
                resources: {}
status: {}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
    creationTimestamp: null
    name: B
    namespace: default
spec:
    template:
        metadata:
            creationTimestamp: null
            labels:
                group__backend: "true"
        spec:
            domain:
                devices: {}
                resources: {}
status: {}
