# permissions for end users to edit migratensxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: migratensx-editor-role
rules:
- apiGroups:
  - nsx.npguard.io
  resources:
  - migratensxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nsx.npguard.io
  resources:
  - migratensxes/status
  verbs:
  - get
