---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nsx.npguard.io
  resources:
  - migratensxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nsx.npguard.io
  resources:
  - migratensxes/finalizers
  verbs:
  - update
- apiGroups:
  - nsx.npguard.io
  resources:
  - migratensxes/status
  verbs:
  - get
  - patch
  - update
