---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nsx.npguard.io
  resources:
  - nsxmigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nsx.npguard.io
  resources:
  - nsxmigrations/finalizers
  verbs:
  - update
- apiGroups:
  - nsx.npguard.io
  resources:
  - nsxmigrations/status
  verbs:
  - get
  - patch
  - update
