apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
    name: New-VM-1
    namespace: default
spec:
    template:
        metadata:
            labels:
                group__no-group-vms-group: "true"
                tag__bar: "true"
        spec:
            domain:
                devices: {}
                resources: {}
status: {}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
    name: New-VM-2
    namespace: default
spec:
    template:
        metadata:
            labels:
                group__nested-expr-group: "true"
                tag__backend: "true"
        spec:
            domain:
                devices: {}
                resources: {}
status: {}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
    name: New-VM-3
    namespace: default
spec:
    template:
        metadata:
            labels:
                group__no-group-vms-group: "true"
                tag__foo: "true"
        spec:
            domain:
                devices: {}
                resources: {}
status: {}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
    name: New-VM-4
    namespace: default
spec:
    template:
        metadata:
            labels:
                group__nested-expr-group: "true"
                tag__bar: "true"
                tag__foo: "true"
        spec:
            domain:
                devices: {}
                resources: {}
status: {}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
    name: NewVirtualMachine
    namespace: default
spec:
    template:
        metadata:
            labels:
                group__research-test-expr-2: "true"
        spec:
            domain:
                devices: {}
                resources: {}
status: {}
