apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
    name: A
    namespace: default
spec:
    template:
        metadata:
            labels:
                VMs_within_IPs__192.168.10.5: "true"
                group__A-by-IP: "true"
                group__frontend: "true"
        spec:
            domain:
                devices: {}
                resources: {}
status: {}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
    name: B
    namespace: default
spec:
    template:
        metadata:
            labels:
                group__backend: "true"
        spec:
            domain:
                devices: {}
                resources: {}
status: {}
