apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
    annotations:
        description: Admin Network Policy To Allow Egress Access To DNS Server
        nsx-id: none
    creationTimestamp: null
    name: egress-dns-policy
spec:
    egress:
        - action: Allow
          ports:
            - portNumber:
                port: 53
                protocol: UDP
          to:
            - pods:
                namespaceSelector: {}
                podSelector:
                    matchExpressions:
                        - key: k8s-app
                          operator: In
                          values:
                            - kube-dns
    priority: 1
    subject:
        pods:
            namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: default
            podSelector: {}
status:
    conditions: null
