apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
    annotations:
        description: '(jump_to_application: (src: (group = Gryffindor) dst: (group = Gryffindor) conn: All Connections)'
        nsx-id: "10218"
    creationTimestamp: null
    name: admin-policy-0
    namespace: default
spec:
    egress:
        - action: Pass
          ports: null
          to:
            - pods:
                namespaceSelector: {}
                podSelector:
                    matchExpressions:
                        - key: group__Gryffindor
                          operator: Exists
    priority: 1
    subject:
        pods:
            namespaceSelector: {}
            podSelector:
                matchExpressions:
                    - key: group__Gryffindor
                      operator: Exists
status:
    conditions: null
---
apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
    annotations:
        description: '(jump_to_application: (src: (group = Gryffindor) dst: (group = Gryffindor) conn: All Connections)'
        nsx-id: "10218"
    creationTimestamp: null
    name: admin-policy-1
    namespace: default
spec:
    ingress:
        - action: Pass
          from:
            - pods:
                namespaceSelector: {}
                podSelector:
                    matchExpressions:
                        - key: group__Gryffindor
                          operator: Exists
          ports: null
    priority: 2
    subject:
        pods:
            namespaceSelector: {}
            podSelector:
                matchExpressions:
                    - key: group__Gryffindor
                      operator: Exists
status:
    conditions: null
---
apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
    annotations:
        description: '(jump_to_application: (src: (group = Hufflepuff) dst: (group = Hufflepuff) conn: All Connections)'
        nsx-id: "10219"
    creationTimestamp: null
    name: admin-policy-2
    namespace: default
spec:
    egress:
        - action: Pass
          ports: null
          to:
            - pods:
                namespaceSelector: {}
                podSelector:
                    matchExpressions:
                        - key: group__Hufflepuff
                          operator: Exists
    priority: 3
    subject:
        pods:
            namespaceSelector: {}
            podSelector:
                matchExpressions:
                    - key: group__Hufflepuff
                      operator: Exists
status:
    conditions: null
---
apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
    annotations:
        description: '(jump_to_application: (src: (group = Hufflepuff) dst: (group = Hufflepuff) conn: All Connections)'
        nsx-id: "10219"
    creationTimestamp: null
    name: admin-policy-3
    namespace: default
spec:
    ingress:
        - action: Pass
          from:
            - pods:
                namespaceSelector: {}
                podSelector:
                    matchExpressions:
                        - key: group__Hufflepuff
                          operator: Exists
          ports: null
    priority: 4
    subject:
        pods:
            namespaceSelector: {}
            podSelector:
                matchExpressions:
                    - key: group__Hufflepuff
                      operator: Exists
status:
    conditions: null
---
apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
    annotations:
        description: '(jump_to_application: (src: (group = Slytherin) dst: (group = Slytherin) conn: All Connections)'
        nsx-id: "10220"
    creationTimestamp: null
    name: admin-policy-4
    namespace: default
spec:
    egress:
        - action: Pass
          ports: null
          to:
            - pods:
                namespaceSelector: {}
                podSelector:
                    matchExpressions:
                        - key: group__Slytherin
                          operator: Exists
    priority: 5
    subject:
        pods:
            namespaceSelector: {}
            podSelector:
                matchExpressions:
                    - key: group__Slytherin
                      operator: Exists
status:
    conditions: null
---
apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
    annotations:
        description: '(jump_to_application: (src: (group = Slytherin) dst: (group = Slytherin) conn: All Connections)'
        nsx-id: "10220"
    creationTimestamp: null
    name: admin-policy-5
    namespace: default
spec:
    ingress:
        - action: Pass
          from:
            - pods:
                namespaceSelector: {}
                podSelector:
                    matchExpressions:
                        - key: group__Slytherin
                          operator: Exists
          ports: null
    priority: 6
    subject:
        pods:
            namespaceSelector: {}
            podSelector:
                matchExpressions:
                    - key: group__Slytherin
                      operator: Exists
status:
    conditions: null
---
apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
    annotations:
        description: '(jump_to_application: (src: (group = Dumbledore) dst: (group = Gryffindor) conn: All Connections)'
        nsx-id: "10221"
    creationTimestamp: null
    name: admin-policy-6
    namespace: default
spec:
    egress:
        - action: Pass
          ports: null
          to:
            - pods:
                namespaceSelector: {}
                podSelector:
                    matchExpressions:
                        - key: group__Gryffindor
                          operator: Exists
    priority: 7
    subject:
        pods:
            namespaceSelector: {}
            podSelector:
                matchExpressions:
                    - key: group__Dumbledore
                      operator: Exists
status:
    conditions: null
---
apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
    annotations:
        description: '(jump_to_application: (src: (group = Dumbledore) dst: (group = Gryffindor) conn: All Connections)'
        nsx-id: "10221"
    creationTimestamp: null
    name: admin-policy-7
    namespace: default
spec:
    ingress:
        - action: Pass
          from:
            - pods:
                namespaceSelector: {}
                podSelector:
                    matchExpressions:
                        - key: group__Dumbledore
                          operator: Exists
          ports: null
    priority: 8
    subject:
        pods:
            namespaceSelector: {}
            podSelector:
                matchExpressions:
                    - key: group__Gryffindor
                      operator: Exists
status:
    conditions: null
---
apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
    annotations:
        description: '(deny: (src: (*) dst: (*) conn: All Connections)'
        nsx-id: "10300"
    creationTimestamp: null
    name: admin-policy-8
    namespace: default
spec:
    egress:
        - action: Deny
          ports: null
          to:
            - pods:
                namespaceSelector: {}
                podSelector: {}
    priority: 9
    subject:
        pods:
            namespaceSelector: {}
            podSelector: {}
status:
    conditions: null
---
apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
    annotations:
        description: '(deny: (src: (*) dst: (*) conn: All Connections)'
        nsx-id: "10300"
    creationTimestamp: null
    name: admin-policy-9
    namespace: default
spec:
    ingress:
        - action: Deny
          from:
            - pods:
                namespaceSelector: {}
                podSelector: {}
          ports: null
    priority: 10
    subject:
        pods:
            namespaceSelector: {}
            podSelector: {}
status:
    conditions: null
