apiVersion: nsx.npguard.io/v1alpha1
kind: NSXMigration
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: nsxmigration-sample-2
spec:
  # TODO(user): Add fields here
  url: ''
  secret:
    name: 'test'
    namespace: 'default'
