apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
    name: A
    namespace: default
spec:
    template:
        metadata:
            labels:
                group__frontend: "true"
        spec:
            domain:
                devices: {}
                resources: {}
status: {}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
    name: B
    namespace: default
spec:
    template:
        metadata:
            labels:
                group__backend: "true"
        spec:
            domain:
                devices: {}
                resources: {}
status: {}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
    name: C
    namespace: default
spec:
    template:
        metadata:
            labels:
                group__frontend1: "true"
        spec:
            domain:
                devices: {}
                resources: {}
status: {}
