name: push-tests-fail-fast

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test-fail-fast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      with:
        go-version-file: ./go.mod

    - name: Build
      run: make build

    - name: Test-Fail-Fast
      run: make test-fail-fast
